apiVersion: apps/v1
kind: Deployment
metadata:
  name: dips-fhir-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dips-fhir-service  
  template:
    metadata:
      labels:
        app: dips-fhir-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: dips-fhir-service
        image: thorstenbaek/dips-fhir-service:v1.0.0.0 
        ports:        
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dips-fhir-service
  labels:
    name: dips-fhir-service
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: dips-fhir-service # => http://dips-fhir-service.norwayeast.cloudapp.azure.com/
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dips-fhir-service