apiVersion: v1
kind: Service
metadata:
    name: "k8sakscluster-3d51"
    labels:
        app: "k8sakscluster-3d51"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "k8sakscluster-3d51"